#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Naoki Otsubo
# SPDX-License-Identifier : BSD-3-Clause

import csv 
import sys

from pathlib import Path

data_dir = Path(__file__).resolve().parent / "data"
csv_path = data_dir / "players.csv"

players = {}
teamnum = {}

with csv_path.open(encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        name = row["name"].strip()
        team = row["team"].strip()
        number = row["number"].strip()
        players[name] = f"{name},{team},{number}"
        teamnum[f"{team},{number}"] = f"{name},{team},{number}"


hit = False
for line in sys.stdin:
    q = line.strip()

    if q in players:
        print(players[q])
        hit = True
    elif q in teamnum:
        print(teamnum[q])
        hit = True

if not hit:
    print("not found", file=sys.stderr)
    sys.exit(1)







